### ISSUE TITLE
Scraping the UK Web Archive with Boilerpipe

### ISSUE THREAD

**Issue by lizfischer** [programminghistorian/ph-submissions#514]
The Programming Historian has received the following tutorial on 'Scraping the UK Web Archive with Boilerpipe' by Caio Mello @caiocmello and Martin Steer @martysteer. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/en/drafts/originals/scraping-the-uk-web-archive-with-boilerpipe

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. 

Our dedicated Ombudsperson is (Ian Milligan - http://programminghistorian.org/en/project-team). Please feel free to contact him at any time if you have concerns that you would like addressed by an impartial observer. Contacting the ombudsperson will have no impact on the outcome of any peer review.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. Thank you for helping us to create a safe space.

---

**Comment by anisa-hawes** [comment]
Hello @lizfischer. Just to let you know that I've sent @martysteer an invitation to join ph-submissions as an outside collaborator for the duration of this lesson's review. (@caiocmello already has write access because they're working on other lessons at the moment). 

This means that both authors will be able to make direct edits to this lesson within our work-in-progress repo, without using the PR system 🙂

**Comment by anisa-hawes** [comment]
Hello again @lizfischer,

I've made a couple of adjustments to the YAML header, and added in the liquid syntax we require to display images on our site (example): `{% include figure.html filename="file-name.png" alt="Visual description of figure image" caption="Caption text to display" %}`. I've plotted in the minimum, and we can return to add descriptive alt-text during the review process. 

I've also made a couple of small typesetting tweaks, and removed the author bios + suggested citation (these are generated automatically).

I'll paste the author bios below (and Alex will slot them into `ph_authors.yml` when we reach publication): 

```
- name: Caio Mello
  team: false
  orcid: 0000-0000-1111-1111
  bio:
      en: |
          Caio Mello is a PhD student in Digital Humanities at the School of Advanced Study, University of London. His main research interests lie in the field of digital methods, Natural Language Processing techniques, data visualisation, media studies, urban studies and digital activism.
```

```
- name: Martin Steer
  team: false
  orcid: 0000-0000-1111-1111
  bio:
      en: |
          Martin Steer is Technical Lead in the Digital Humanities Research Hub at the School of Advanced Study, University of London. He works with humanities and social media data, data infrastructure, web archives and fiction.
```

A live preview of the lesson is now available: http://programminghistorian.github.io/ph-submissions/en/drafts/originals/scraping-the-uk-web-archive-with-boilerpipe
